---
detectors:
  TooManyStatements:
    max_statements: 7
  UncommunicativeVariableName:
    enabled: false
  FeatureEnvy:
    exclude:
      - fetch_last_id
      - last_item
      - update_time_columns
  TooManyMethods:
    max_methods: 20
    exclude:
      - ValidationEditor
  LongParameterList:
    exclude:
      - process_and_update_time_field
      - invalid_time_value?
  DataClump:
    exclude:
      - TimeValidationHelpers