AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - timet.gemspec

Metrics/MethodLength:
  Max: 15

plugins: rubocop-rspec

RSpec/ExampleLength:
  Max: 15 

Metrics/CyclomaticComplexity:
  Max: 8

RSpec/MultipleMemoizedHelpers:
  Max: 15
