AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - timet.gemspec

Metrics/MethodLength:
  Max: 12

require: rubocop-rspec

RSpec/ExampleLength:
  Max: 10 

Metrics/CyclomaticComplexity:
  Max: 8
