name: Rubocop

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*
      
jobs:
  run-linters:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2

    - name: Set up ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.1

    - name: Gems Cache
      id: gem-cache
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: Install dependencies
      run: bundle install --jobs 4 --retry 3

    - name: Run linters
      uses: wearerequired/lint-action@v1
      with:
        github_token: ${{ secrets.github_token }}
        rubocop: true
        rubocop_command_prefix: bundle exec
        rubocop_args: -c ./.rubocop.yml
